---
- name: Despliegue de la aplicación
  hosts: servidor
  become: yes

  vars:
    app_name: myapp
    app_dir: /var/www/{{ app_name }}
    app_repo: https://github.com/tu_usuario/tu_repositorio.git
    app_version: master

  tasks:
    # Instalación de dependencias
    - name: Instalación de Node.js
      apt:
        name: nodejs
        state: present

    - name: Instalación de npm
      apt:
        name: npm
        state: present

    - name: Instalación de PM2
      npm:
        name: pm2
        global: yes

    # Descarga de la aplicación
    - name: Descarga de la aplicación
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dir }}"
        version: "{{ app_version }}"

    # Instalación de dependencias de la aplicación
    - name: Instalación de dependencias de la aplicación
      npm:
        path: "{{ app_dir }}"
        production: yes

    # Inicio de la aplicación con PM2
    - name: Inicio de la aplicación
      command: pm2 start {{ app_dir }}/index.js --name "{{ app_name }}"
